### ISSUE TITLE
mov2mov与Additional Networks扩展冲突了，希望解决一下。

### ISSUE THREAD

**Issue by ilikeulinux** [Scholar01/sd-webui-mov2mov#1]
![QQ图片20230228112535](https://user-images.githubusercontent.com/41497656/221745672-e167c950-c283-4143-8dbc-fb89429c277e.png)
使用lora必须要Additional Networks

**Comment by zhuoruofuqu** [comment]
冲突了，应用并重启web UI后在图生图界面没有mov2mov选项卡
Error loading script: main.py
Traceback (most recent call last):
  File "D:\NovelAI-Stable Diffusion\stable-diffusion-webui_23-01-20\stable-diffusion-webui_23-01-20\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\NovelAI-Stable Diffusion\stable-diffusion-webui_23-01-20\stable-diffusion-webui_23-01-20\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\NovelAI-Stable Diffusion\stable-diffusion-webui_23-01-20\stable-diffusion-webui_23-01-20\extensions\sd-webui-mov2mov\scripts\main.py", line 13, in <module>
    from scripts.util import video_to_images, images_to_video
ImportError: cannot import name 'video_to_images' from 'scripts.util' (D:\NovelAI-Stable Diffusion\stable-diffusion-webui_23-01-20\stable-diffusion-webui_23-01-20\extensions\sd-webui-additional-networks\scripts\util.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Scholar01** [comment]
已经修复
