### ISSUE TITLE
m2m_ui.py error

### ISSUE THREAD

**Issue by wyyzxml2120** [Scholar01/sd-webui-mov2mov#104]
Load script m2m for extension sd-webii-mov2mov_ Ui.py failed.

**Comment by javarike** [comment]
`AddNet] Updating model hashes...
Error loading script: m2m_ui.py
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd-webui-aki-v4\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd-webui-aki-v4\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 12, in <module>
    from modules import (
ImportError: cannot import name 'ui_prompt_styles' from 'modules' (unknown location)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error loading script: module_ui_extensions.py
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd-webui-aki-v4\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd-webui-aki-v4\extensions\sd-webui-mov2mov\scripts\module_ui_extensions.py", line 53, in <module>
    obj=ui_components.InputAccordion,
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Error loading script: movie_editor.py
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\sd-webui-aki-v4\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sd-webui-aki-v4\extensions\sd-webui-mov2mov\scripts\movie_editor.py", line 9, in <module>
    from modules.ui_components import InputAccordion, ToolButton
ImportError: cannot import name 'InputAccordion' from 'modules.ui_components' (D:\sd-webui-aki-v4\modules\ui_components.py)`

webui:v1.6.0

**Comment by shenmingik** [comment]
解决了吗？我用的colab，失败了

**Comment by ENTPRESTIGIOUS** [comment]
Same on v1.5.2

**Comment by scooller** [comment]
same error on v1.9.0

**Comment by theSplund** [comment]
Hit the same problem in 1.9.3

**Comment by roigh** [comment]
im in the same spot in 1.10.1
