### ISSUE TITLE
Mov2mov crash and controlnet crash

### ISSUE THREAD

**Issue by keithbandit98** [Scholar01/sd-webui-mov2mov#121]
Automatic1111: version 1.6.1
ControlNet v1.1.419
no other extensions installed except for controlnet and mov2mov
python 3.10.6
torch: 2.0.1+cu118 
xformers: N/A 
gradio: 3.41.2
checkpoint: [76be5be1b2]

FIRST PROBLEM:
Randomly at the begin the software work but i t launch this error, sometimes can show it some times not:
THE ERROR:
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.1
Commit hash: <none>
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
C:\ai\stable-diffusion-webui_1.6.1\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension C:\ai\stable-diffusion-webui_1.6.1\extensions\sd-webui-mov2mov.
*** Command: "C:\ai\stable-diffusion-webui_1.6.1\venv\Scripts\python.exe" "C:\ai\stable-diffusion-webui_1.6.1\extensions\sd-webui-mov2mov\install.py"
*** Error code: 1
*** stdout: Installing requirements for Mov2mov
*** Installing requirements for imageio-ffmpeg
***
*** stderr: Traceback (most recent call last):
***   File "C:\ai\stable-diffusion-webui_1.6.1\extensions\sd-webui-mov2mov\install.py", line 15, in <module>
***     launch.run_pip("install imageio-ffmpeg", "requirements for imageio-ffmpeg")
***   File "C:\ai\stable-diffusion-webui_1.6.1\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\ai\stable-diffusion-webui_1.6.1\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for imageio-ffmpeg.
*** Command: "C:\ai\stable-diffusion-webui_1.6.1\venv\Scripts\python.exe" -m pip install imageio-ffmpeg --prefer-binary
*** Error code: 3221225477
*** stdout: Requirement already satisfied: imageio-ffmpeg in c:\ai\stable-diffusion-webui_1.6.1\venv\lib\site-packages (0.4.9)
*** Requirement already satisfied: setuptools in c:\ai\stable-diffusion-webui_1.6.1\venv\lib\site-packages (from imageio-ffmpeg) (63.2.0)
***
Launching Web UI with arguments:
2023-11-30 21:47:53,350 - ControlNet - INFO - ControlNet v1.1.419
ControlNet preprocessor location: C:\ai\stable-diffusion-webui_1.6.1\extensions\sd-webui-controlnet\annotator\downloads
2023-11-30 21:47:53,417 - ControlNet - INFO - ControlNet v1.1.419
Loading weights [76be5be1b2] from C:\ai\stable-diffusion-webui_1.6.1\models\Stable-diffusion\epicrealism_pureEvolutionV5.safetensors
Creating model from config: C:\ai\stable-diffusion-webui_1.6.1\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 13.6s (prepare environment: 10.5s, other imports: 0.5s, setup codeformer: 0.1s, load scripts: 1.6s, create ui: 0.3s, gradio launch: 0.5s).
Applying attention optimization: Doggettx... done.
Model loaded in 1.7s (load weights from disk: 0.4s, create model: 0.2s, apply weights to model: 1.0s).

SECOND PROBLEM:
Automatic1111 very often crash when i launch mov2mov and controlnet together, they work together only 1 on 10 attempts...
Other attempts can run only mov2mov without controlnet randomly but it cant complete the process that it crash randomly... im very frustrating cause i use video of 20 seconds with 15-30fps and low resolution 960*540 but i have a tons of problems... and the worst thing is all RANDOM every crash or error is random !!!! pleas help to find a stability maybe im using the wrong version extension of controlnet? or wrong version of AUTOMATIC1111?? or other?

**Comment by optera15** [comment]
There is a massive memory leak. I can watch it leak frame by frame till my GPU explodes and Wndows11 dies. This should be super easy to find and fix. Just stop leaking every frame, please!
