### ISSUE TITLE
TypeError: 'StableDiffusionProcessingImg2Img' object is not callable

### ISSUE THREAD

**Issue by mantosssss** [Scholar01/sd-webui-mov2mov#124]
When trying to use ReActor in the mov2mov integration, right after generating, I get the following error:
TypeError: 'StableDiffusionProcessingImg2Img' object is not callable

log

Start parsing the number of mov frames
The video conversion is completed, images:344
current progress: 1/344
*** Error completing request
*** Arguments: ('task(wlyvatso27a2llh)', '', '', [], 'C:\\Users\\simon\\AppData\\Local\\Temp\\gradio\\ca1acdd0b1dbdbc066d0c3939de228fa2716901c\\2023-12-11 15-56-48.mkv', 20, 'pndm', 7, 1.5, 0, 512, 512, 0, [], 1, 60, -1.0, False,    id  frame prompt
*** 0   0      0       , 4, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <PIL.Image.Image image mode=RGB size=620x620 at 0x1D4F7FDED10>, True, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CPU', True, 0, 'None', '', None, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 267, in mov2mov
        generate_video = process_mov2mov(p, mov_file, movie_frames, max_frames, resize_mode, width, height, args)
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 90, in process_mov2mov
        processed = process_images(p)
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images
        res = process_images_inner(p)
      File "C:\Windows\System32\sd-test\stable-diffusion-webui-directml\modules\processing.py", line 794, in process_images_inner
        return p()
    TypeError: 'StableDiffusionProcessingImg2Img' object is not callable

**Comment by Supersnu** [comment]
Same error for me!

Start parsing the number of mov frames
The video conversion is completed, images:24429
current progress: 1/24429
*** Error completing request
*** Arguments: ('task(6b6nus133in3w7v)', '', '', [], 'C:\\Users\\Daheim\\AppData\\Local\\Temp\\gradio\\5cda003294c5445baa16aed791fbc3d1b3e66028\\05.mp4', 20, 'pndm', 7, 1.5, 0, 240, 426, 0, [], 0, 24, -1.0, False,    id  frame prompt
*** 0   0      0       , 4, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, None, True, '0', '0', 'inswapper_128.onnx', 'CodeFormer', 1, True, 'None', 1, 1, False, True, 1, 0, 0, False, 0.5, True, False, 'CPU', False, 1, 'Sandra.safetensors', '', None, False, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\sd-gpu\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\sd-gpu\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\sd-gpu\stable-diffusion-webui-directml\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 267, in mov2mov
        generate_video = process_mov2mov(p, mov_file, movie_frames, max_frames, resize_mode, width, height, args)
      File "D:\sd-gpu\stable-diffusion-webui-directml\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 90, in process_mov2mov
        processed = process_images(p)
      File "D:\sd-gpu\stable-diffusion-webui-directml\modules\processing.py", line 735, in process_images
        res = process_images_inner(p)
      File "D:\sd-gpu\stable-diffusion-webui-directml\modules\processing.py", line 796, in process_images_inner
        return p()
    TypeError: 'StableDiffusionProcessingImg2Img' object is not callable
