### ISSUE TITLE
Error loading script: m2m_ui.py

### ISSUE THREAD

**Issue by 158zd** [Scholar01/sd-webui-mov2mov#146]
Windows:10
Python:3.10.6
Version:v1.9.0
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/162105571/a50e862b-53c7-41a3-98e1-ad9c1fb6c4be)
"I followed this method to reinstall m2m_ui.py, but the same error persists."
![image](https://github.com/Scholar01/sd-webui-mov2mov/assets/162105571/d37b19ac-e126-4391-b136-5763bb747006)

**Comment by jcvijr** [comment]
Same here

**Comment by bahamute00** [comment]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "D:\01-유틸\99-SD_webUI\sd.webui\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\01-유틸\99-SD_webUI\sd.webui\webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\01-유틸\99-SD_webUI\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (D:\01-유틸\99-SD_webUI\sd.webui\webui\modules\ui.py)  
    
    same here

**Comment by BigShaka77** [comment]
Yes, it worked! Thank you.......I didn't do the last step and it worked perfectly.

**Comment by mickmick69** [comment]
> Same here
> 
> Edit: I've created a very rough workaround for this issue, since I don't know mov2mov code. I've noticed lots of changes happened in A1111 implementation, and the create_sampler_and_steps_selection() function in A1111 ui.py just vanished.
> 
> I created the same function again inside m2m_ui.py, getting those settings from txt2img tab. [m2m_ui.zip](https://github.com/Scholar01/sd-webui-mov2mov/files/14972506/m2m_ui.zip)
> 
> You will need to set in txt2img tab those settings too, in order to mov2mov work.

Thanx, Now I have mov2mov tab in my interface but I am not sure what do you mean by "need to set in txt2img tab those settings too, in order to mov2mov work"

What should I change in txt2img tab ?

**Comment by tshr-d-dragon** [comment]
Just copy this function in modules/ui.py

```
def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
```

**Comment by ildoddo** [comment]
> Just copy this function in modules/ui.py
> 
> ```
> def create_sampler_and_steps_selection(choices, tabname):
>     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> ```

This worked for me! Thanks

**Comment by gsw85** [comment]
> Just copy this function in modules/ui.py
> 
> ```
> def create_sampler_and_steps_selection(choices, tabname):
>     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> ```

This solved! Thanks 
I just add this 
```python
def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
``` 

in \Stable Diffusion WebUI\modules\ui.py

**Comment by Chau867** [comment]
> > Just copy this function in modules/ui.py
> > ```
> > def create_sampler_and_steps_selection(choices, tabname):
> >     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> > ```
> 
> This solved! Thanks I just add this
> 
> ```python
> def create_sampler_and_steps_selection(choices, tabname):
>     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> ```
> 
> in \Stable Diffusion WebUI\modules\ui.py

im sorry, which line i could add it in, im just normal user :))

**Comment by tshr-d-dragon** [comment]
@158zd close the issue

**Comment by xiaoooan** [comment]
> 只需將這個函數複製到modules/ui.py中
> 
> ```
> def create_sampler_and_steps_selection(choices, tabname):
>     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> ```

I just copy m2m_ui.py to extensions\sd-webui-mov2mov\scripts to overwrite the old one, and enable Stable Diffusion to display M2M normally.

**Comment by tshr-d-dragon** [comment]
> > 只需將這個函數複製到modules/ui.py中
> > ```
> > def create_sampler_and_steps_selection(choices, tabname):
> >     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> > ```
> 
> I just copy m2m_ui.py to extensions\sd-webui-mov2mov\scripts to overwrite the old one, and enable Stable Diffusion to display M2M normally.

You can try stable diffusion webui version 1.7.0 too.

**Comment by theSplund** [comment]
I can confirm that the two-part solution has it working in 1.9.3, (at least for me) - and it wasn't as tricky as it first looked!

**Comment by benknam** [comment]
> Just copy this function in modules/ui.py
> 
> ```
> def create_sampler_and_steps_selection(choices, tabname):
>     return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
> ```

Works  PERFECTLY！！ 厉害了老铁！！！👍🏻

**Comment by servicexyz123** [comment]
very much useful, For https://github.com/Scholar01/sd-webui-mov2mov, just replace script m2m_ui.py with  [m2m_ui.zip](https://github.com/Scholar01/sd-webui-mov2mov/files/14972506/m2m_ui.zip)
For https://github.com/DavG25/sd-webui-mov2mov
insert:
def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name
s

**Comment by DarshanSahay** [comment]
Nothing seems to work for me tbh. Tried pasting code , tried replacing the file but still no success. SD version 1.9.3

**Comment by EdnaMode22** [comment]
> Nothing seems to work for me tbh. Tried pasting code , tried replacing the file but still no success. SD version 1.9.3

Yeah I'm having the same issue I've tried everything mentioned with a similar error code,

**Comment by woojoo87** [comment]
how can i fix this error??

*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "E:\sd\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "E:\sd\stable-diffusion-webui\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "E:\sd\stable-diffusion-webui\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'

**Comment by metalarcher794** [comment]
I have the same error like woojoo87 I try eveything I update and still nothing need help thank you

**Comment by zuumi** [comment]
Indeed, it seems that the `create_sampler_and_steps_selection` method has been deleted in the following commit:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/25cd53d77561fda3dbfd6c280f0d2852cb162bda#diff-e20573334d898aca3a51188e89e2fee20a9273a1139fabe3ec8ca762969f2293L232

The problem was solved by using `stable-diffusion-webui` with a version such as v1.8.0.

**Comment by loveonce** [comment]
Same Issue not resolve after replace "m2m_ui.py" file or add the code in ui.py "def create_sampler_and_steps_selection(choices, tabname):
    return scripts.scripts_txt2img.script('Sampler').steps, scripts.scripts_txt2img.script('Sampler').sampler_name"


Still Issue same 
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "D:\AI\webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\webui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 48, in <module>
        from scripts import mov2mov
      File "D:\AI\webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "D:\AI\webui\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "D:\AI\webui\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'


*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "D:\AI\webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI\webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "D:\AI\webui\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "D:\AI\webui\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'


**Python 3.10.6**
**pip 22.2.1**
**Windows 11**


Some one help to resolve this issue
