### ISSUE TITLE
Error !!

### ISSUE THREAD

**Issue by liuxb99** [Scholar01/sd-webui-mov2mov#157]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "E:\AI\sd-webui-aki-v4.8\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\AI\sd-webui-aki-v4.8\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\AI\sd-webui-aki-v4.8\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (E:\AI\sd-webui-aki-v4.8\modules\ui.py)

---

**Comment by QuentinRiviere** [comment]
https://github.com/Scholar01/sd-webui-mov2mov/issues/145#issuecomment-2065992830

**Comment by Scholar01** [comment]
It has been fixed. If you have other problems, please submit a new issue.
