### ISSUE TITLE
mov2mov didnt work

### ISSUE THREAD

**Issue by zeegeit** [Scholar01/sd-webui-mov2mov#158]
i got this error 

*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "D:\Hafizh\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Hafizh\stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Hafizh\stable diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "D:\Hafizh\stable diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "D:\Hafizh\stable diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'

**Comment by QuentinRiviere** [comment]
# Reason

The bug comes from the file `extensions/sd-webui-mov2mov/ebsynth/ebsynth_generate.py`
https://github.com/Scholar01/sd-webui-mov2mov/blob/e4e96e7836159b5a58794a1bdf0acce31b9b1271/ebsynth/ebsynth_generate.py#L5

It is referenced but not used in the code if you look below

https://github.com/Scholar01/sd-webui-mov2mov/blob/e4e96e7836159b5a58794a1bdf0acce31b9b1271/ebsynth/ebsynth_generate.py#L127


# Workaround

In `extensions/sd-webui-mov2mov/ebsynth/ebsynth_generate.py` comment the line `from toolz import groupby` 

```python
import cv2
import numpy as np
from PIL.Image import Image
from dataclasses import dataclass, field
# from toolz import groupby  <--- HERE

```

**Comment by Scholar01** [comment]
It has been fixed. If you have other problems, please submit a new issue.
