### ISSUE TITLE
FFMPEG not installed error, but it is

### ISSUE THREAD

**Issue by adng83** [Scholar01/sd-webui-mov2mov#161]
error in mov2mov / automatic1111

Traceback (most recent call last):
      File "C:\SDW\sd.webui\webui\modules\call_queue.py", line 74, in f
        res = list(func(*args, **kwargs))
      File "C:\SDW\sd.webui\webui\modules\call_queue.py", line 53, in f
        res = func(*args, **kwargs)
      File "C:\SDW\sd.webui\webui\modules\call_queue.py", line 37, in f
        res = func(*args, **kwargs)
      File "C:\SDW\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 267, in mov2mov
        generate_video = process_mov2mov(p, mov_file, movie_frames, max_frames, resize_mode, width, height, args)
      File "C:\SDW\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 95, in process_mov2mov
        video = save_video(generate_images, movie_frames)
      File "C:\SDW\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 48, in save_video
        video = images_to_video(images, fps,
      File "C:\SDW\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\m2m_util.py", line 83, in images_to_video
        return images_to_video_imageio(images, frames, out_path, 'libx264')
      File "C:\SDW\sd.webui\webui\extensions\sd-webui-mov2mov\scripts\m2m_util.py", line 97, in images_to_video_imageio
        with imageio.v2.get_writer(out_path, format='ffmpeg', mode='I', fps=frames, codec=codec) as writer:
      File "C:\SDW\sd.webui\webui\venv\lib\site-packages\imageio\v2.py", line 324, in get_writer
        image_file = imopen(uri, "w" + mode, **imopen_args)
      File "C:\SDW\sd.webui\webui\venv\lib\site-packages\imageio\core\imopen.py", line 156, in imopen
        raise err_type(err_msg) from err_from
    ImportError: The `FFMPEG` plugin is not installed. Use `pip install imageio[ffmpeg]` to install it.

when i punch that command into powershell i get:

PS C:\SDW\sd.webui\webui> pip install imageio[ffmpeg]
Requirement already satisfied: imageio[ffmpeg] in c:\users\[username]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (2.36.0)
Requirement already satisfied: numpy in c:\users\[username]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio[ffmpeg]) (1.26.4)
Requirement already satisfied: pillow>=8.3.2 in c:\users\[username]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio[ffmpeg]) (10.3.0)
Requirement already satisfied: imageio-ffmpeg in c:\users\[username]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio[ffmpeg]) (0.5.1)
Requirement already satisfied: psutil in c:\users\[username]\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from imageio[ffmpeg]) (6.0.0)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages (from imageio-ffmpeg->imageio[ffmpeg]) (65.5.0)

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\[username]\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

i have installed version: pip3 install imageio==2.33 as that is the only one that seems to satisfy all requirements. 

ffmpeg is a path with variable : C:\FFmpeg / value of: C:\FFmpeg

please can someone tell me what is going wrong!

the odd thing is it is generating images in the mov2mov/pictures folder, the issue is when it tries to stitch it back together at the very end of the process 

Ffmpeg also works fine with other extensions

**Comment by adng83** [comment]
Fixed: I had a no update flag i my arguments
