### ISSUE TITLE
sd-webui-mov2mov tab does not show up on Automatic1111 SD v1.10.1

### ISSUE THREAD

**Issue by fafayqa** [Scholar01/sd-webui-mov2mov#164]
I am on SD 1.10.1, I installed sd-webui-mov2mov but the tab does not show up at all.
Can anyone tell me what to do, please?

This is the error log from the CMD window (I am on Win10 x64 Enterprise LTSC):

Restarting UI...
Closing server running on port: 7860
*** Error loading script: base_ui.py
    Traceback (most recent call last):
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\extensions\SD-CN-Animation\scripts\base_ui.py", line 16, in <module>
        from modules.ui import setup_progressbar, create_sampler_and_steps_selection, ordered_ui_categories, create_output_panel
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\ui.py)

---
2024-12-21 12:44:07,519 - ControlNet - INFO - ControlNet v1.1.455
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 23, in <module>
        from modules.ui import (
    ImportError: cannot import name 'create_sampler_and_steps_selection' from 'modules.ui' (Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\ui.py)

---
*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "Z:\_PSTART_\_APPS_\_AI_\Automatic1111\stable-diffusion-webui-1.10\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'

---
2024-12-21 12:44:07,704 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

**Comment by chicman** [comment]
Same here!

**Comment by akerbel** [comment]
I could fix the errors, but don't know yet if everything really works, or just GUI.

1. Go to _stable-diffusion-webui\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py_ , find the line "from toolz import groupby" and put # at the beging of the line. Looks like module "toolz" was deleted, but somebody forgot to remove its importing.
2. Go to _stable-diffusion-webui\modules\ui.py_ and add this code at the end of the file: https://github.com/kairin/stable-diffusion-webui-forge/commit/a6566082cf9788d2630796baa4430dfe34d70f3c#diff-e20573334d898aca3a51188e89e2fee20a9273a1139fabe3ec8ca762969f2293R1086

It is only temporal solution.

**Comment by suget** [comment]
When will the author adapt to the recent SD

**Comment by Scholar01** [comment]
It has been fixed. If you have other problems, please submit a new issue.
