### ISSUE TITLE
    ModuleNotFoundError: No module named 'toolz'

### ISSUE THREAD

**Issue by w10-l** [Scholar01/sd-webui-mov2mov#165]
*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "F:\sd-webui-aki\sd-webui-aki-v4.10\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "F:\sd-webui-aki\sd-webui-aki-v4.10\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\sd-webui-aki\sd-webui-aki-v4.10\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 24, in <module>
        from ebsynth import EbsynthGenerate, Keyframe
      File "F:\sd-webui-aki\sd-webui-aki-v4.10\extensions\sd-webui-mov2mov\ebsynth\__init__.py", line 2, in <module>
        from .ebsynth_generate import EbsynthGenerate, Keyframe, Sequence, EbSynthTask
      File "F:\sd-webui-aki\sd-webui-aki-v4.10\extensions\sd-webui-mov2mov\ebsynth\ebsynth_generate.py", line 5, in <module>
        from toolz import groupby
    ModuleNotFoundError: No module named 'toolz'

**Comment by Scholar01** [comment]
It has been fixed. If you have other problems, please submit a new issue.
