### ISSUE TITLE
RGBA 转换错误  

### ISSUE THREAD

**Issue by cndavy** [Scholar01/sd-webui-mov2mov#4]
jpg 建议转成 png

**Comment by nicehero** [comment]
我这里也发生了这个错误，第一次用是好的，后来再勾选
Apply color correction to img2img results to match original colors.
后报错
Traceback (most recent call last):
  File "C:\ai\novelai-webui-aki-v2\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\ai\novelai-webui-aki-v2\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\ai\novelai-webui-aki-v2\extensions\sd-webui-mov2mov\scripts\main.py", line 19, in foo
    return hookfunc(*args, **kwargs)
  File "C:\ai\novelai-webui-aki-v2\extensions\sd-webui-mov2mov\scripts\main.py", line 161, in mov2mov
    result = img2img(id_task, mode, prompt, negative_prompt, prompt_styles, init_img, sketch,
  File "C:\ai\novelai-webui-aki-v2\modules\img2img.py", line 163, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "C:\ai\novelai-webui-aki-v2\modules\img2img.py", line 76, in process_batch
    processed_image.save(os.path.join(output_dir, filename))
  File "C:\ai\novelai-webui-aki-v2\py310\lib\site-packages\PIL\Image.py", line 2431, in save
    save_handler(self, fp, filename)
  File "C:\ai\novelai-webui-aki-v2\py310\lib\site-packages\PIL\JpegImagePlugin.py", line 646, in _save
    raise OSError(msg) from e
OSError: cannot write mode RGBA as JPEG
