### ISSUE TITLE
[libopenh264 @ 0000020e85fdf080] Incorrect library version loaded

### ISSUE THREAD

**Issue by ameen-roayan** [Scholar01/sd-webui-mov2mov#43]
Hello ! 

I get this error after the process is done. 

Start generating .mp4 file
[libopenh264 @ 0000020e85fdf080] Incorrect library version loaded
[ERROR:2@5180.519] global /build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2822) open Could not open codec libopenh264, error: Unspecified error
[ERROR:2@5180.519] global /build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2839) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
The generation is complete, the directory::outputs/mov2mov-videos\1681738708.mp4
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1991, in postprocess
    y = self.make_temp_copy_if_needed(y)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos\\1681738708.mp4'

**Comment by merecesarchviz** [comment]
same here, how we can solve this?
