### ISSUE TITLE
...py310\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file     with open(file_path, "rb") as f: FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by athrony** [Scholar01/sd-webui-mov2mov#54]
有时候好用 有时候不好用，刚才还能用，突然就不行了，开始是第二张图时候报错，后面变成第三张报错
感觉是用locon时候就报这个错，后面换lora没报错，但是加了关键字又报这个错
-------------
Traceback (most recent call last):
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1012, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\components.py", line 1991, in postprocess
    y = self.make_temp_copy_if_needed(y)
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\processing_utils.py", line 362, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "E:\tools\stable\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------
python: 3.10.8  •  torch: 2.0.0+cu118  •  xformers: 0.0.17rc482  •  gradio: 3.23.0

**Comment by Scholar01** [comment]
感觉像是你的显存炸了
