### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by CarribbeanLover** [Scholar01/sd-webui-mov2mov#57]
Error executing callback ui_tabs_callback for L:\AiWorkSpace\StableDiffusionWebUI\extensions\sd-webui-mov2mov\scripts\m2m_ui.py
Traceback (most recent call last):
  File "L:\AiWorkSpace\StableDiffusionWebUI\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "L:\AiWorkSpace\StableDiffusionWebUI\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 323, in on_ui_tabs
    generate_mov_mode,
UnboundLocalError: local variable 'generate_mov_mode' referenced before assignment

**Comment by synthscribe** [comment]
Im getting the same error. been looking for hours now, still havnt found a fix
