### ISSUE TITLE
(-215:Assertion failed) number < max_number in function 'icvExtractPattern'

### ISSUE THREAD

**Issue by dil27** [Scholar01/sd-webui-mov2mov#70]
Just tried this extension, after generating images then I got this errors when it generate .mp4 file:
```
Start generating .mp4 file
[ERROR:0@2735.120] global cap_ffmpeg_impl.hpp:2991 open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@2735.120] global cap_ffmpeg_impl.hpp:3066 open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[ERROR:0@2735.194] global cap.cpp:595 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'


The generation is complete, the directory::outputs/mov2mov-videos/1684820171.mp4

Total progress: 100% 1200/1200 [27:23<00:00,  1.37s/it]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 956, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 1888, in postprocess
    y = self.make_temp_copy_if_needed(y)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 379, in make_temp_copy_if_needed
    temp_file_path = self.get_temp_file_path(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 365, in get_temp_file_path
    file_hash = self.hash_file(file_path)
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 334, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/mov2mov-videos/1684820171.mp4'
```

Do I installed wrong OpenCV ?
`!pip -q install opencv-python`

Sorry to open this new Issue if exists, Not be a racist but I'm having trouble to find the same issues as mine here because mostly are in Chinese 😂😅

**Comment by hhhxmm** [comment]
try xvid or mp4v. similar errors occur when I use H264 encoding.
