### ISSUE TITLE
mov2mov conflicts with controlnet

### ISSUE THREAD

**Issue by WhiteGL** [Scholar01/sd-webui-mov2mov#79]
ontrolnet extension at commit 8e143d35 with v1.1 models, mov2mov at commit 0ba11a1a. Controlnet doesn't work when mov2mov is activated. The bug report is as below:

2023-08-22 08:17:11,190 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().
*** Error running postprocess_batch: D:\SD-web\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\SD-web\sd-webui-aki-v4\modules\scripts.py", line 506, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
    TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: D:\SD-web\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py
    Traceback (most recent call last):
      File "D:\SD-web\sd-webui-aki-v4\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error running postprocess: D:\SD-web\sd-webui-aki-v4\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py
    Traceback (most recent call last):
      File "D:\SD-web\sd-webui-aki-v4\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
    TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by min-star** [comment]
the same problem

**Comment by dkamajix** [comment]
having the same here with A1111 V1.52+ controlnet + mov2mov - get the warning error for controlnet

**Comment by Scholar01** [comment]
Please try the new version

**Comment by ktee95** [comment]
> Please try the new version

anyfix for lastest Vlad fork WebUI, mov2mov keep missing in UI
