### ISSUE TITLE
添加之后启动报错

### ISSUE THREAD

**Issue by dengrixionghnu** [Scholar01/sd-webui-mov2mov#84]
Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "/Users/apple/ai/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/apple/ai/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/apple/ai/stable-diffusion-webui/extensions/sd-webui-mov2mov/scripts/m2m_ui.py", line 12, in <module>
        from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
    ImportError: cannot import name 'create_seed_inputs' from 'modules.ui'

**Comment by cyberdenz** [comment]
Broken starting v1.6.0-RC
using (https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.2) works!

**Comment by hiarivic** [comment]
hey how's it going? I'm using google colab, how do I put this older version? because whenever I start the session it automatically downloads the latest version. Would you be able to help me please?

**Comment by Scholar01** [comment]
新版本修复了

**Comment by cyberdenz** [comment]
After it is fixed on 1.6.0, now broken on v1.5.2... :-)
