### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ''

### ISSUE THREAD

**Issue by suchacutesnake** [Scholar01/sd-webui-mov2mov#9]
我使用的autodl云端的Linux服务器，启动后报错如下：
```
Start converting video, frame number:12
mov2mov_images_path：/root/autodl-tmp/stable-diffusion-webui/outputs/mov2mov-images
current_mov2mov_images_path：/root/autodl-tmp/stable-diffusion-webui/outputs/mov2mov-images/1677864863
The video conversion is completed, frames:12, images:139
Error completing request
Arguments: ('task(60n20ne74t12x2e)', 0, '', '', [], None, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', 0, True, '/tmp/km5__1opy2.mp4', 0, False, 10, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, 0, 512, 512, False, False, True, True, True, False, False, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, False) {}
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/root/autodl-tmp/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/mov2mov/scripts/main.py", line 19, in foo
    return hookfunc(*args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/mov2mov/scripts/main.py", line 161, in mov2mov
    result = img2img(id_task, mode, prompt, negative_prompt, prompt_styles, init_img, sketch,
  File "/root/autodl-tmp/stable-diffusion-webui/modules/img2img.py", line 156, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/img2img.py", line 22, in process_batch
    images = shared.listfiles(input_dir)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/shared.py", line 669, in listfiles
    filenames = [os.path.join(dirname, x) for x in sorted(os.listdir(dirname)) if not x.startswith(".")]
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by suchacutesnake** [comment]
更新以后没这个问题了，问题变成了启动时给出以下信息：
```
Error loading script: m2m_ui.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/mov2mov/scripts/m2m_ui.py", line 12, in <module>
    from modules.ui import paste_symbol, clear_prompt_symbol, extra_networks_symbol, apply_style_symbol, save_style_symbol, \
ImportError: cannot import name 'create_override_settings_dropdown' from 'modules.ui' (/root/autodl-tmp/stable-diffusion-webui/modules/ui.py)

Error loading script: mov2mov.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/root/autodl-tmp/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/mov2mov/scripts/mov2mov.py", line 8, in <module>
    from modules.generation_parameters_copypaste import create_override_settings_dict
ImportError: cannot import name 'create_override_settings_dict' from 'modules.generation_parameters_copypaste' (/root/autodl-tmp/stable-diffusion-webui/modules/generation_parameters_copypaste.py)
```

**Comment by suchacutesnake** [comment]
怀疑不是这个插件的问题，尝试更新一下webui
