### ISSUE TITLE
error and movie coming out like a grey blob

### ISSUE THREAD

**Issue by Itchy-Fingaz** [Scholar01/sd-webui-mov2mov#91]
*** Error running before_process_batch: /Users/chief/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/Users/chief/stable-diffusion-webui/modules/scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "/Users/chief/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 43, in before_process_batch
        if params.enable and isinstance(p, StableDiffusionProcessingImg2Img):
    AttributeError: 'NoneType' object has no attribute 'enable'

Using Automatic1111 on M1

**Comment by Scholar01** [comment]
You seem to have asked in the wrong place, this is not my plug-in
