### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by Elytzh** [Scholar01/sd-webui-mov2mov#94]
*** Error loading script: m2m_ui.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\m2m_ui.py", line 12, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

---
*** Error loading script: m2m_util.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\m2m_util.py", line 2, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

---
*** Error loading script: mov2mov.py
    Traceback (most recent call last):
      File "D:\stable-diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 7, in <module>
        from rich import print
    ModuleNotFoundError: No module named 'rich'

**Comment by Elytzh** [comment]
nvm guys it worked using fork feel free https://github.com/DavG25/sd-webui-mov2mov
