### ISSUE TITLE
Adding mov2mov breaks multi controlnet

### ISSUE THREAD

**Issue by palvarez19** [Scholar01/sd-webui-mov2mov#95]
I found that installing mov2mov prevents me from using controlnet. I found this while controlnet in img2img. Removing mov2mov makes everything work again. I get the following errors:

``
2023-09-24 13:04:09,584 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: (False, 'Colored Pencil Art', <scripts.animatediff_ui.AnimateDiffProcess object at 0x7fda80ae9f00>).
2023-09-24 13:04:09,585 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: (False, 'Colored Pencil Art', <scripts.animatediff_ui.AnimateDiffProcess object at 0x7fda80ae9f00>).
*** Error running process: /home/test/sd3/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py
    Traceback (most recent call last):
      File "/home/test/sd3/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/home/test/sd3/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 154, in process
        int(x) for x in faces_index.strip(",").split(",") if x.isnumeric()
    AttributeError: 'UiControlNetUnit' object has no attribute 'strip'

---
*** Error running before_process_batch: /home/test/sd3/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/test/sd3/stable-diffusion-webui/modules/scripts.py", line 627, in before_process_batch
        script.before_process_batch(p, *script_args, **kwargs)
      File "/home/test/sd3/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 42, in before_process_batch
        if params.enable and isinstance(p, StableDiffusionProcessingImg2Img):
    AttributeError: 'bool' object has no attribute 'enable'

---
100%|█████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  6.87it/s]
*** Error running postprocess_image: /home/test/sd3/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py]
    Traceback (most recent call last):
      File "/home/test/sd3/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/home/test/sd3/stable-diffusion-webui/extensions/sd-webui-roop/scripts/faceswap.py", line 187, in postprocess_image
        faces_index=self.faces_index,
    AttributeError: 'FaceSwapScript' object has no attribute 'faces_index'

---
*** Error running postprocess: /home/test/sd3/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
    Traceback (most recent call last):
      File "/home/test/sd3/stable-diffusion-webui/modules/scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/home/test/sd3/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 49, in postprocess
        if params.enable:
    AttributeError: 'bool' object has no attribute 'enable'

``

**Comment by Scholar01** [comment]
sd-webui-animatediff?

**Comment by palvarez19** [comment]
I don't know why I get errors about other extensions after installing mov2mov, but perhaps I should try removing them and see what happens

**Comment by Scholar01** [comment]
already fixed
