### ISSUE TITLE
Out of Vram but I have 24gb 4090 rtx

### ISSUE THREAD

**Issue by techmd84** [Scholar01/sd-webui-mov2mov#98]
I tired everything turning off my 2 displays, closing everything, got it to 1.4gb before starting sd, but still out of vram, tried messing with all the settings, its a 14 sec clip!

Start parsing the number of mov frames
The video conversion is completed, images:219
current progress: 1/219
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.42it/s]
*** Error completing request                                                         | 10/2190 [00:01<04:08,  8.76it/s]
*** Arguments: ('task(rvtepk5uwat1dpd)', 'dancing  girl', '', 'C:\\Users\\dusti\\AppData\\Local\\Temp\\gradio\\79de4bcb8781c653cc4986565cdf714305a083a1\\1.mp4', 30, 'Euler a', True, False, False, None, None, 'none', 0, 1, 10, 1, 0, 7, 1.5, 0.3, 10, -1.0, 924, 528, 1, [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000242FA8568F0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000242BDD2CF70>, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, '', False, 'Normal', 1, True, 1, 1, 'None', False, False, False, 'YuNet', 512, 1024, 0.5, 1.5, False, 'face close up,', 0.5, 0.5, False, True, None, None, False, None, None, False, 50, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, False, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 2, 0, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000242BDD2C580>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000242BDD2EEF0>, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, '', False, 'Normal', 1, True, 1, 1, 'None', False, False, False, 'YuNet', 512, 1024, 0.5, 1.5, False, 'face close up,', 0.5, 0.5, False, True, None, None, False, None, None, False, 50, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, False, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 2, 0, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation') {}
    Traceback (most recent call last):
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 260, in mov2mov
        generate_video = process_mov2mov(p, mov_file, movie_frames, max_frames, resize_mode, width, height,
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\extensions\sd-webui-mov2mov\scripts\mov2mov.py", line 108, in process_mov2mov
        processed = process_images(p)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\processing.py", line 914, in process_images_inner
        x_sample = modules.face_restoration.restore_faces(x_sample)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\face_restoration.py", line 19, in restore_faces        return face_restorer.restore(np_image)
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\codeformer_model.py", line 81, in restore
        self.create_models()
      File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\modules\codeformer_model.py", line 58, in create_models        checkpoint = torch.load(ckpt_path)['params_ema']
    KeyError: 'params_ema'

---
Traceback (most recent call last):
  File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "C:\Users\dusti\Documents\A111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (mov2mov) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [gallery, video, textbox, html, html]
Received outputs:
    [None, "", "", "<div class='error'>KeyError: &#x27;params_ema&#x27;</div><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>2.5 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>5.58 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>6.14 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>8.8/23.9883 GB</span> (36.5%)</p></div>"]

**Comment by techmd84** [comment]
Unchecking restore faces worked.  I think I took most extensions off because they where causing mov2mov not to show up... weird!

**Comment by Scholar01** [comment]
Should it be fixed?
